apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: stock-cron
    name: stock-cron
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: stock-cron
    template:
        metadata:
            labels:
                app: stock-cron
        spec:
            containers:
                - name: stock-cron
                  image: us.gcr.io/typescript-study-2020-10-30/default/stock-cron:latest
---
# stock-cron Expose
apiVersion: v1
kind: Service
metadata:
    name: stock-cron
    namespace: default
    labels:
        app: stock-cron
spec:
    ports:
        - protocol: TCP
          port: 8080
          nodePort: 30100
    selector:
        app: stock-cron
    type: NodePort
